### PR TITLE
Add GMT_IS_REFERENCE to the GMT_Open_VirtualFile call

### PR DESCRIPTION
**Pull request by PaulWessel**
Since we are passing complete GMT containers.

### CODE REVIEW

**Comment by joa-quim** [comment]
What will happen if the gmtmex is run with 6.0 dll/so/dylib?

**Comment by PaulWessel** [comment]
Probably should declare a mismatch. gmtmex (new version?) requires 6.1.

**Comment by PaulWessel** [comment]
We are still on 1.0.0.  Seems we need to bump this to 1.1.0 to go with 6.1?

**Comment by PaulWessel** [comment]
We have been a bit sloppy about versions of externals and versions of GMT.  Clearly, version x of some external may not work forever with all future GMT versions, hence we must update them.

**Comment by joa-quim** [comment]
Yes, but besides that, what I want to know is if this change is backward incompatible.

**Comment by PaulWessel** [comment]
It probably is.  There were several "design bugs" where we said one thing but did another under the hood, such as saying GMT_IS_REFERENCE is allowed but then overturned it inside gmt_api.c because doing so led to a crash.  I fixed all those problems so that we can read grids from matrices, with subsets, etc. etc., so now, VF items are GMT_IS_DUPLICATE by default (which is was because of the bugs) and now if you add GMT_IS_REFERENCE you do indeed pass via reference, unless that is not possible (like passing a char matrix as a grid).  If there is no pad on your reference and you call grdimage then we deal with taht instead of exiting.  So all is much better, but of course I cannot fix those problems without breaking the "broken" past.  So clearly time to draw a line and up the version numbers of the externals for 6.1

**Comment by joa-quim** [comment]
The point is also that if it turns out to be backward incompatible we should call it 2.0 instead of 1.1

**Comment by PaulWessel** [comment]
Yes, you are right, and we should be consistent on this.  We have made lots of changes to mex over the last 2 years and still 1.0.0.  So lets decide it is 2.0.0 for 6.1 release.  Can't we also check internally in gmtmex that gmt version is at least 6.1 and stop if not?

**Comment by joa-quim** [comment]
Sure we should (and need) be able to check that. I can look at it tomorrow.

**Comment by PaulWessel** [comment]
I can probably do this today and let you know if problematic.  We added and API function for this I think (for Julia)

**Comment by PaulWessel** [comment]
Because GMTMEX now needs GMT 6.1 we have upped the version of GMTMEX to 2.0.0, and there is now a check to ensure that the GMT library used is at least 6.1.0.  Most of the changes relates to dates and versions and this check, in addition to the earlier fix to the single _GMT_Open_VirtualFile_ call.  With those changes (and the latest GMT version that addressed the GDAL netcdf HDF5 file reading", all of the 2017 examples and tests for GMT/MEX passes.

**Review by joa-quim — APPROVED** [review]

**Pull request merged**
